/**
 * Build the cascade resolver into a single IIFE string for page injection.
 * Output: src/resolverBundleCode.ts (auto-generated, DO NOT EDIT)
 *
 * Usage: npx tsx scripts/build-resolver.ts
 */
import * as esbuild from 'esbuild';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

async function buildResolverBundle() {
  const result = await esbuild.build({
    entryPoints: [resolve(__dirname, '../resolver-bundle/entry.ts')],
    bundle: true,
    write: false,
    format: 'iife',
    globalName: '__browserletResolver',
    platform: 'browser',
    target: 'es2020',
    minify: false, // Keep readable for debugging
  });

  const code = new TextDecoder().decode(result.outputFiles[0].contents);

  // Write as a TypeScript module exporting the string constant
  const outputPath = resolve(__dirname, '../src/resolverBundleCode.ts');
  writeFileSync(
    outputPath,
    `// AUTO-GENERATED by scripts/build-resolver.ts -- DO NOT EDIT\n` +
    `// Regenerate with: npx tsx scripts/build-resolver.ts\n` +
    `export const RESOLVER_BUNDLE = ${JSON.stringify(code)};\n`
  );

  console.log(`Resolver bundle written to ${outputPath} (${code.length} bytes)`);
}

buildResolverBundle().catch((err) => {
  console.error('Build failed:', err);
  process.exit(1);
});
