import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { JSDOM } from 'jsdom';
import { looksLikeHashedClass, looksAutoGenerated, generateHints } from '../../../entrypoints/content/recording/hintGenerator';

// Set up DOM environment for generateHints tests
let dom: JSDOM;

beforeEach(() => {
  dom = new JSDOM('<!DOCTYPE html><html><body></body></html>', {
    url: 'http://localhost/',
  });
  global.document = dom.window.document;
  global.window = dom.window as unknown as Window & typeof globalThis;
  global.HTMLElement = dom.window.HTMLElement;
  global.Element = dom.window.Element;
  global.Node = dom.window.Node;
});

afterEach(() => {
  dom.window.close();
});

describe('looksLikeHashedClass', () => {
  describe('should detect CSS Module hashed classes', () => {
    it('styles__name___hash pattern', () => {
      expect(looksLikeHashedClass('styles__onEnd___1mc8z')).toBe(true);
      expect(looksLikeHashedClass('styles__button___abc12')).toBe(true);
      expect(looksLikeHashedClass('components__header___xY9kL')).toBe(true);
    });

    it('name__hash pattern (double underscore + hash suffix)', () => {
      expect(looksLikeHashedClass('login__a3f2d')).toBe(true);
      expect(looksLikeHashedClass('header__xB9kZ')).toBe(true);
      expect(looksLikeHashedClass('nav__item__abcdef')).toBe(true);
    });
  });

  describe('should detect styled-components classes', () => {
    it('sc-* pattern', () => {
      expect(looksLikeHashedClass('sc-abc123')).toBe(true);
      expect(looksLikeHashedClass('sc-bdnxRM')).toBe(true);
      expect(looksLikeHashedClass('sc-a')).toBe(true);
    });
  });

  describe('should detect Emotion classes', () => {
    it('css-* pattern', () => {
      expect(looksLikeHashedClass('css-1a2b3c')).toBe(true);
      expect(looksLikeHashedClass('css-k008qs')).toBe(true);
      expect(looksLikeHashedClass('css-0')).toBe(true);
    });
  });

  describe('should detect generic CSS-in-JS hashed classes', () => {
    it('double underscore with hash-like suffix', () => {
      expect(looksLikeHashedClass('module__component_a3f2d1')).toBe(true);
      expect(looksLikeHashedClass('app__sidebar_xk29mz')).toBe(true);
    });
  });

  describe('should NOT filter legitimate semantic classes', () => {
    it('simple component classes', () => {
      expect(looksLikeHashedClass('login-form')).toBe(false);
      expect(looksLikeHashedClass('btn-primary')).toBe(false);
      expect(looksLikeHashedClass('header-nav')).toBe(false);
      expect(looksLikeHashedClass('sidebar')).toBe(false);
      expect(looksLikeHashedClass('main-content')).toBe(false);
    });

    it('BEM-style classes (single underscore separator)', () => {
      expect(looksLikeHashedClass('block_element')).toBe(false);
      expect(looksLikeHashedClass('nav-item')).toBe(false);
      expect(looksLikeHashedClass('card-body')).toBe(false);
    });

    it('classes with numbers that are not hashes', () => {
      expect(looksLikeHashedClass('heading-1')).toBe(false);
      expect(looksLikeHashedClass('col-12')).toBe(false);
      expect(looksLikeHashedClass('step-3')).toBe(false);
    });

    it('common framework classes', () => {
      expect(looksLikeHashedClass('container')).toBe(false);
      expect(looksLikeHashedClass('row')).toBe(false);
      expect(looksLikeHashedClass('modal-dialog')).toBe(false);
      expect(looksLikeHashedClass('form-control')).toBe(false);
      expect(looksLikeHashedClass('alert-danger')).toBe(false);
    });
  });
});

describe('looksAutoGenerated', () => {
  describe('should detect CSS Module ID patterns', () => {
    it('styles__name___hash as ID', () => {
      expect(looksAutoGenerated('styles__onEnd___1mc8z')).toBe(true);
      expect(looksAutoGenerated('styles__button___abc12')).toBe(true);
    });
  });

  describe('should still detect other auto-generated patterns', () => {
    it('UUIDs', () => {
      expect(looksAutoGenerated('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
    });

    it('React-style IDs', () => {
      expect(looksAutoGenerated('react-123')).toBe(true);
      expect(looksAutoGenerated(':r1:')).toBe(true);
    });

    it('hex hash IDs', () => {
      expect(looksAutoGenerated('a1b2c3d4e5')).toBe(true);
    });
  });

  describe('should NOT filter stable IDs', () => {
    it('human-readable IDs', () => {
      expect(looksAutoGenerated('userfield')).toBe(false);
      expect(looksAutoGenerated('passwordfield')).toBe(false);
      expect(looksAutoGenerated('login-form')).toBe(false);
      expect(looksAutoGenerated('submit-btn')).toBe(false);
    });
  });

  describe('Vue/Angular ID filtering', () => {
    it('should filter Vue 3 colon-wrapper SSR IDs', () => {
      expect(looksAutoGenerated(':r0:')).toBe(true);
      expect(looksAutoGenerated(':r1a:')).toBe(true);
      expect(looksAutoGenerated(':rN:')).toBe(true);
    });

    it('should filter Angular generated IDs', () => {
      expect(looksAutoGenerated('ng-component-id')).toBe(true);
      expect(looksAutoGenerated('ng_model_1')).toBe(true);
    });

    it('should NOT filter stable IDs with ng-like words in content', () => {
      expect(looksAutoGenerated('login-form')).toBe(false);
      expect(looksAutoGenerated('settings-page')).toBe(false);
    });
  });
});

// ---------------------------------------------------------------------------
// generateHints - landmark_context
// ---------------------------------------------------------------------------

describe('generateHints - landmark_context', () => {
  it('should capture landmark_context for element inside <nav>', () => {
    document.body.innerHTML = `
      <nav>
        <button id="menu-btn">Menu</button>
      </nav>
    `;
    const btn = document.getElementById('menu-btn')!;
    const hints = generateHints(btn);
    const landmark = hints.find(h => h.type === 'landmark_context');
    expect(landmark).toBeDefined();
    expect(landmark?.value).toBe('navigation');
  });

  it('should capture landmark_context for element inside <main>', () => {
    document.body.innerHTML = `
      <main>
        <button id="submit-btn">Submit</button>
      </main>
    `;
    const btn = document.getElementById('submit-btn')!;
    const hints = generateHints(btn);
    const landmark = hints.find(h => h.type === 'landmark_context');
    expect(landmark).toBeDefined();
    expect(landmark?.value).toBe('main');
  });

  it('should NOT emit landmark_context for element outside any landmark', () => {
    document.body.innerHTML = `<div><button id="btn">Click</button></div>`;
    const btn = document.getElementById('btn')!;
    const hints = generateHints(btn);
    const landmark = hints.find(h => h.type === 'landmark_context');
    expect(landmark).toBeUndefined();
  });

  it('should capture landmark_context for element inside [role="search"]', () => {
    document.body.innerHTML = `
      <div role="search">
        <input id="q" type="search">
      </div>
    `;
    const input = document.getElementById('q')!;
    const hints = generateHints(input);
    const landmark = hints.find(h => h.type === 'landmark_context');
    expect(landmark).toBeDefined();
    expect(landmark?.value).toBe('search');
  });
});

// ---------------------------------------------------------------------------
// generateHints - Vue/Angular data attribute filtering
// ---------------------------------------------------------------------------

describe('generateHints - Vue/Angular data attribute filtering', () => {
  it('should NOT emit data_attribute hint for Vue scoped data-v-* attributes', () => {
    document.body.innerHTML = `<button id="btn" data-v-3a4b5c67="true">Click</button>`;
    const btn = document.getElementById('btn')!;
    const hints = generateHints(btn);
    const vueScopedHint = hints.find(
      h => h.type === 'data_attribute' &&
      typeof h.value === 'object' &&
      (h.value as { name: string }).name === 'data-v-3a4b5c67'
    );
    expect(vueScopedHint).toBeUndefined();
  });

  it('should NOT emit data_attribute hint for Angular _ngcontent-* attributes', () => {
    document.body.innerHTML = `<button id="btn" _ngcontent-abc-c0="">Click</button>`;
    const btn = document.getElementById('btn')!;
    const hints = generateHints(btn);
    const ngHint = hints.find(
      h => h.type === 'data_attribute' &&
      typeof h.value === 'object' &&
      (h.value as { name: string }).name.startsWith('_ngcontent-')
    );
    expect(ngHint).toBeUndefined();
  });

  it('should still emit data_attribute hint for data-testid', () => {
    document.body.innerHTML = `<button id="btn" data-testid="submit-btn">Click</button>`;
    const btn = document.getElementById('btn')!;
    const hints = generateHints(btn);
    const testIdHint = hints.find(
      h => h.type === 'data_attribute' &&
      typeof h.value === 'object' &&
      (h.value as { name: string; value: string }).name === 'data-testid'
    );
    expect(testIdHint).toBeDefined();
    expect((testIdHint?.value as { name: string; value: string }).value).toBe('submit-btn');
  });
});
