import { describe, it, expect } from 'vitest';
import { looksLikeHashedClass, looksAutoGenerated } from '../../../entrypoints/content/recording/hintGenerator';

describe('looksLikeHashedClass', () => {
  describe('should detect CSS Module hashed classes', () => {
    it('styles__name___hash pattern', () => {
      expect(looksLikeHashedClass('styles__onEnd___1mc8z')).toBe(true);
      expect(looksLikeHashedClass('styles__button___abc12')).toBe(true);
      expect(looksLikeHashedClass('components__header___xY9kL')).toBe(true);
    });

    it('name__hash pattern (double underscore + hash suffix)', () => {
      expect(looksLikeHashedClass('login__a3f2d')).toBe(true);
      expect(looksLikeHashedClass('header__xB9kZ')).toBe(true);
      expect(looksLikeHashedClass('nav__item__abcdef')).toBe(true);
    });
  });

  describe('should detect styled-components classes', () => {
    it('sc-* pattern', () => {
      expect(looksLikeHashedClass('sc-abc123')).toBe(true);
      expect(looksLikeHashedClass('sc-bdnxRM')).toBe(true);
      expect(looksLikeHashedClass('sc-a')).toBe(true);
    });
  });

  describe('should detect Emotion classes', () => {
    it('css-* pattern', () => {
      expect(looksLikeHashedClass('css-1a2b3c')).toBe(true);
      expect(looksLikeHashedClass('css-k008qs')).toBe(true);
      expect(looksLikeHashedClass('css-0')).toBe(true);
    });
  });

  describe('should detect generic CSS-in-JS hashed classes', () => {
    it('double underscore with hash-like suffix', () => {
      expect(looksLikeHashedClass('module__component_a3f2d1')).toBe(true);
      expect(looksLikeHashedClass('app__sidebar_xk29mz')).toBe(true);
    });
  });

  describe('should NOT filter legitimate semantic classes', () => {
    it('simple component classes', () => {
      expect(looksLikeHashedClass('login-form')).toBe(false);
      expect(looksLikeHashedClass('btn-primary')).toBe(false);
      expect(looksLikeHashedClass('header-nav')).toBe(false);
      expect(looksLikeHashedClass('sidebar')).toBe(false);
      expect(looksLikeHashedClass('main-content')).toBe(false);
    });

    it('BEM-style classes (single underscore separator)', () => {
      expect(looksLikeHashedClass('block_element')).toBe(false);
      expect(looksLikeHashedClass('nav-item')).toBe(false);
      expect(looksLikeHashedClass('card-body')).toBe(false);
    });

    it('classes with numbers that are not hashes', () => {
      expect(looksLikeHashedClass('heading-1')).toBe(false);
      expect(looksLikeHashedClass('col-12')).toBe(false);
      expect(looksLikeHashedClass('step-3')).toBe(false);
    });

    it('common framework classes', () => {
      expect(looksLikeHashedClass('container')).toBe(false);
      expect(looksLikeHashedClass('row')).toBe(false);
      expect(looksLikeHashedClass('modal-dialog')).toBe(false);
      expect(looksLikeHashedClass('form-control')).toBe(false);
      expect(looksLikeHashedClass('alert-danger')).toBe(false);
    });
  });
});

describe('looksAutoGenerated', () => {
  describe('should detect CSS Module ID patterns', () => {
    it('styles__name___hash as ID', () => {
      expect(looksAutoGenerated('styles__onEnd___1mc8z')).toBe(true);
      expect(looksAutoGenerated('styles__button___abc12')).toBe(true);
    });
  });

  describe('should still detect other auto-generated patterns', () => {
    it('UUIDs', () => {
      expect(looksAutoGenerated('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
    });

    it('React-style IDs', () => {
      expect(looksAutoGenerated('react-123')).toBe(true);
      expect(looksAutoGenerated(':r1:')).toBe(true);
    });

    it('hex hash IDs', () => {
      expect(looksAutoGenerated('a1b2c3d4e5')).toBe(true);
    });
  });

  describe('should NOT filter stable IDs', () => {
    it('human-readable IDs', () => {
      expect(looksAutoGenerated('userfield')).toBe(false);
      expect(looksAutoGenerated('passwordfield')).toBe(false);
      expect(looksAutoGenerated('login-form')).toBe(false);
      expect(looksAutoGenerated('submit-btn')).toBe(false);
    });
  });
});
